<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Suite1" duration-ms="23723" started-at="2017-08-11T09:53:06Z" finished-at="2017-08-11T09:53:30Z">
    <groups>
    </groups>
    <test name="Nopackage" duration-ms="23723" started-at="2017-08-11T09:53:06Z" finished-at="2017-08-11T09:53:30Z">
      <class name="MainTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:MainTest@3fb6a447]" name="setUp" is-config="true" duration-ms="3322" started-at="2017-08-11T12:53:06Z" finished-at="2017-08-11T12:53:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="checkContainerPage()[pri:0, instance:MainTest@3fb6a447]" name="checkContainerPage" duration-ms="10816" started-at="2017-08-11T12:53:10Z" finished-at="2017-08-11T12:53:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkContainerPage -->
        <test-method status="PASS" signature="findBVapi()[pri:0, instance:MainTest@3fb6a447]" name="findBVapi" duration-ms="3628" started-at="2017-08-11T12:53:20Z" finished-at="2017-08-11T12:53:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- findBVapi -->
        <test-method status="PASS" signature="gotoSeleniumWikiPage()[pri:0, instance:MainTest@3fb6a447]" name="gotoSeleniumWikiPage" duration-ms="2737" started-at="2017-08-11T12:53:24Z" finished-at="2017-08-11T12:53:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- gotoSeleniumWikiPage -->
        <test-method status="FAIL" signature="gotoSeleniumWikiPageFailure()[pri:0, instance:MainTest@3fb6a447]" name="gotoSeleniumWikiPageFailure" duration-ms="2346" started-at="2017-08-11T12:53:27Z" finished-at="2017-08-11T12:53:29Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Selenium WebDriver] but found [Selenium]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Selenium WebDriver] but found [Selenium]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at MainTest.gotoSeleniumWikiPageFailure(MainTest.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- gotoSeleniumWikiPageFailure -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:MainTest@3fb6a447]" name="tearDown" is-config="true" duration-ms="845" started-at="2017-08-11T12:53:29Z" finished-at="2017-08-11T12:53:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- MainTest -->
    </test> <!-- Nopackage -->
  </suite> <!-- Suite1 -->
</testng-results>
